services:
  - type: web
    name: n8n
    env: docker
    repo: https://github.com/lonerleo/n8n
    region: singapore
    plan: free
    branch: master
    dockerfilePath: Dockerfile
    envVars:
      - key: N8N_BASIC_AUTH_USER
        value: admin
      - key: N8N_BASIC_AUTH_PASSWORD
        value: admin123
      - key: N8N_HOST
        value: n8n.onrender.com
      - key: N8N_PORT
        value: 5678
      - key: WEBHOOK_URL
        value: https://n8n.onrender.com/
